name:               tasty-bdd
version:            0.1.0.0
synopsis:           BDD tests language and tasty provider
description:        https://gitlab.com/devs.global.de/tasty-bdd/-/blob/master/README.md
homepage:           https://gitlab.com/devs.global.de/tasty-bdd
license:            BSD3
license-file:       LICENSE
author:             Paolo Veronelli, Pavlo Kerestey
maintainer:         paolo.veronelli@gmail.com
copyright:          2017 Paolo Veronelli
category:           Test
extra-source-files: README.md

default-extensions: OverloadedStrings

library:
    source-dirs:   src
    exposed-modules: 
      - Test.Tasty.Bdd
      - Test.BDD.Language
      - Test.BDD.LanguageFree
      - System.CaptureStdout
    ghc-options:     
      - -Wall
    dependencies:    
      - base >= 4.7 && <5
      - exceptions
      - free
      - HUnit
      - microlens
      - microlens-th
      - mtl
      - pretty-show
      - pretty
      - tagged
      - tasty
      - tasty-fail-fast
      - tasty-hunit
      - transformers
      - tree-diff
      - text
      - temporary

tests: 
  test:
    main: Main.hs
    dependencies:   
      - base >= 4.7 && <5
      - exceptions
      - aeson
      - aeson-qq
      - HUnit
      - mtl
      - tasty
      - tasty-hunit
      - tasty-bdd
      - tasty-fail-fast
      - tasty-expected-failure
      - transformers
      - temporary
      - qm-interpolated-string
      - text
      - regex-posix
    source-dirs:   tests
    ghc-options:     
     - -Wall

